# Generated by Django 3.0.8 on 2020-08-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='Logo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
